=== JGuissart/Xml-Exercises/dtd/mcd_small_doc.dtd
<!ELEMENT nom (#PCDATA)>
<!ELEMENT identifiant (#PCDATA)>
<!ELEMENT mcd_small (entite, entite+, association)>
<!ELEMENT entite (nom, attribut)>
<!ELEMENT attribut (identifiant*,nom)>
<!ELEMENT association (nom,attribut, role)>
<!ELEMENT role (identifiant+)>
<!ATTLIST nom cardinaliteMin (0|1) #IMPLIED>
<!ATTLIST nom cardinaliteMax (1|N) #IMPLIED>
<!ATTLIST identifiant cardinaliteMin (0|1) #IMPLIED>
<!ATTLIST identifiant cardinaliteMax (1|N) #IMPLIED>
<!ATTLIST identifiant role CDATA #IMPLIED>
<!ATTLIST mcd_small xmlns CDATA #IMPLIED>

=== JGuissart/Xml-Exercises/ns/mcd_small_doc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mcd_small SYSTEM "../dtd/mcd_small_doc.dtd">
<mcd_small xmlns="/ns/mcd_small">
    <entite>
        <nom>ville</nom>
        <attribut>
            <identifiant>nom</identifiant>
            <nom>population</nom>
        </attribut>	
    </entite>
    <entite>
        <nom >personne</nom>
        <attribut>
            <identifiant>nom</identifiant>
            <nom cardinaliteMin="0" cardinaliteMax="1">naissance</nom>
        </attribut>
    </entite>
    <association>
        <nom>habite</nom>
        <attribut>
            <nom>depuis</nom>
         </attribut>
        <role>
            <identifiant cardinaliteMin="0" cardinaliteMax="N">nom</identifiant>
            <identifiant cardinaliteMin="1" cardinaliteMax="N" role="habitant">nom</identifiant>
        </role>
    </association>
</mcd_small>
